secrets:
  COOKIE_SECRET:
    kind: latest_at_deployment_start
    type: salt
    owner: '@github/docs-engineering'
    externally_usable: true
  CSE_COPILOT_ENDPOINT:
    kind: latest_at_deployment_start
    type: salt
    owner: '@github/docs-engineering'
    externally_usable: true
  CSE_COPILOT_SECRET:
    kind: latest_at_deployment_start
    type: salt
    owner: '@github/docs-engineering'
    externally_usable: true
  DOCS_BOT_PAT_BASE:
    kind: latest_at_deployment_start
    type: github_pat
    owner: '@github/docs-engineering'
    externally_usable: true
  DOCS_BOT_PAT_COPILOT:
    kind: latest_at_deployment_start
    type: github_pat
    owner: '@github/docs-engineering'
    externally_usable: true
  DOCS_BOT_PAT_REPO_SYNC:
    kind: latest_at_deployment_start
    type: github_pat
    owner: '@github/docs-engineering'
    externally_usable: true
  ELASTICSEARCH_URL:
    kind: latest_at_deployment_start
    type: elasticsearch
    owner: '@github/docs-engineering'
    externally_usable: true
  FASTLY_API_TOKEN:
    kind: latest_at_deployment_start
    type: fastly
    owner: '@github/docs-engineering'
    externally_usable: true
  FASTLY_SERVICE_ID:
    kind: latest_at_deployment_start
    type: fastly
    owner: '@github/docs-engineering'
    externally_usable: true
  FASTLY_TOKEN:
    kind: latest_at_deployment_start
    type: fastly
    owner: '@github/docs-engineering'
    externally_usable: true
  HAYSTACK_URL:
    kind: latest_at_deployment_start
    type: failbot
    owner: '@github/docs-engineering'
    externally_usable: true
  HYDRO_ENDPOINT:
    kind: latest_at_deployment_start
    type: hydro_api_key
    owner: '@github/docs-engineering'
    externally_usable: true
  HYDRO_SECRET:
    kind: latest_at_deployment_start
    type: hydro_api_key
    owner: '@github/docs-engineering'
    externally_usable: true
